name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: build
      uses: CultureHQ/actions-yarn@master
      with:
        args: predeploy
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        FOLDER: build
      
