name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: build
      uses: CultureHQ/actions-yarn@master
      with:
        args: predeploy
    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v2.10.1
      with:
        PUBLISH_DIR: ./build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
