name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: deploy
      uses: CultureHQ/actions-yarn@master
      with:
        args: deploy
